//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemoProduct
    {
        public int Si { get; set; }
        public string Product { get; set; }
        public string Brand { get; set; }
        public string Month { get; set; }
        public string State { get; set; }
        public int Value { get; set; }
    }
}
